--- #YAML:1.0
name: Posy-Plugin-ThemeCss
version: 0.42
author:
  - Kathryn Andersen
abstract: Posy plugin for Cascading Style Sheet themes.
license: perl
requires:
  Posy: 0.95
  Posy::Plugin::YamlConfig: 0.41
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::ThemeCss:
    file: lib/Posy/Plugin/ThemeCss.pm
    version: 0.42
generated_by: Module::Build version 0.261
